name:                aoc-haskell
version:             0.1.0.0
github:              "daniel-manning/aoc-haskell"
license:             BSD3
author:              "Daniel Manning"
maintainer:          "example@example.com"
copyright:           "2020 Daniel Manning"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/daniel-manning/aoc-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- parsec
- parser-combinators
- either
- cryptohash-md5
- bytestring
- text
- base16-bytestring
- utf8-string
- MissingH
- containers
- unordered-containers
- hashable
- aeson
- aeson-pretty
- universe-base
- json-stream
- raw-strings-qq
- extra
- psqueues

library:
  source-dirs: src

executables:
  aoc-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-haskell

tests:
  aoc-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - aoc-haskell
